### ISSUE TITLE
Fix flakey test - Submit Add Family form

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4908]
Test disabled in 47c7d36c2aff76178aa02735fed8f6edee9ced95 because of random failure.

**Comment by garethbowen** [comment]
Merged!

**Comment by SCdF** [comment]
This test is still failing for all of my PRs at a very high rate.

**Comment by garethbowen** [comment]
This one is still failing a lot. Recent stacktrace:

```
Failures:
1) Family form Submit Add Family form
  Message:
[31m    Failed: element not interactable
      (Session info: headless chrome=73.0.3683.75)
      (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-101-generic x86_64)[0m
  Stack:
    ElementNotVisibleError: element not interactable
      (Session info: headless chrome=73.0.3683.75)
      (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-101-generic x86_64)
        at Object.checkLegacyResponse (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/error.js:546:15)
        at parseHttpResponse (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/http.js:509:13)
        at doSend.then.response (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/http.js:441:30)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: WebElement.click()
        at thenableWebDriverProxy.schedule (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
        at WebElement.schedule_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
        at WebElement.click (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
        at actionFn (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:89:44)
        at Array.map (<anonymous>)
        at actionResults.getWebElements.then (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:461:65)
        at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:1376:14)
        at TaskQueue.execute_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2927:27)
        at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
        at process._tickCallback (internal/process/next_tick.js:68:7)Error
        at ElementArrayFinder.applyAction_ (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:459:27)
        at ElementArrayFinder.(anonymous function).args [as click] (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:91:29)
        at ElementFinder.(anonymous function).args [as click] (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:831:22)
        at Object.fillSexAndAge (/home/travis/build/medic/medic/tests/page-objects/forms/add-family-form.po.js:46:16)
        at UserContext.it (/home/travis/build/medic/medic/tests/e2e/forms/add-family-form.specs.js:32:16)
        at /home/travis/build/medic/medic/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at schedulerExecute (/home/travis/build/medic/medic/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2974:25)
        at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From: Task: Run it("Submit Add Family form") in control flow
        at UserContext.<anonymous> (/home/travis/build/medic/medic/node_modules/jasminewd2/index.js:94:19)
        at /home/travis/build/medic/medic/node_modules/jasminewd2/index.js:64:48
        at ControlFlow.emit (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/events.js:62:21)
        at ControlFlow.shutdown_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2674:10)
        at shutdownTask_.MicroTask (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2599:53)
        at MicroTask.asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2728:9)
        at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
        at process._tickCallback (internal/process/next_tick.js:68:7)
    From asynchronous test: 
    Error
        at Suite.describe (/home/travis/build/medic/medic/tests/e2e/forms/add-family-form.specs.js:25:3)
        at Object.<anonymous> (/home/travis/build/medic/medic/tests/e2e/forms/add-family-form.specs.js:7:1)
        at Module._compile (internal/modules/cjs/loader.js:701:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
        at Module.load (/home/travis/build/medic/medic/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
        at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
        at Function.Module._load (internal/modules/cjs/loader.js:531:3)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (internal/modules/cjs/helpers.js:22:18)
        at /home/travis/build/medic/medic/node_modules/jasmine/lib/jasmine.js:93:5
        at Array.forEach (<anonymous>)
        at Jasmine.loadSpecs (/home/travis/build/medic/medic/node_modules/jasmine/lib/jasmine.js:92:18)
        at Jasmine.execute (/home/travis/build/medic/medic/node_modules/jasmine/lib/jasmine.js:197:8)
        at /home/travis/build/medic/medic/node_modules/protractor/built/frameworks/jasmine.js:132:15
        at Function.promise (/home/travis/build/medic/medic/node_modules/q/q.js:682:9)
        at /home/travis/build/medic/medic/node_modules/protractor/built/frameworks/jasmine.js:104:14
        at _fulfilled (/home/travis/build/medic/medic/node_modules/q/q.js:834:54)
        at /home/travis/build/medic/medic/node_modules/q/q.js:863:30
        at Promise.promise.promiseDispatch (/home/travis/build/medic/medic/node_modules/q/q.js:796:13)
        at /home/travis/build/medic/medic/node_modules/q/q.js:604:44
        at runSingle (/home/travis/build/medic/medic/node_modules/q/q.js:137:13)
        at flush (/home/travis/build/medic/medic/node_modules/q/q.js:125:13)
        at process._tickCallback (internal/process/next_tick.js:61:11)

264 specs, 1 failure
Finished in 534.537 seconds
```

**Comment by garethbowen** [comment]
Another attempt made. Closing to see if it happens again.

**Comment by dianabarsan** [comment]
This test is failing very frequently: https://github.com/medic/cht-core/actions/runs/4950828143/jobs/8855271053#step:16:736
The error is: 
```
element ("input[name="/data/clinic/household_survey/source_of_drinking_water"]") still not clickable after 15000ms
[chrome 113.0.5672.63 linux #0-15] Error: element ("input[name="/data/clinic/household_survey/source_of_drinking_water"]") still not clickable after 15000ms
```
