### ISSUE TITLE
Travis builds timing out after ~50 minutes when API fails to start

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5196]
https://travis-ci.org/medic/medic-webapp/jobs/474988767

`Ran for 50 min`

```
Checking API
Request failed: connect ECONNREFUSED 127.0.0.1:5988
API check failed, trying again in 5 seconds
...
Checking API
Request failed: connect ECONNREFUSED 127.0.0.1:5988
API check failed, trying again in 5 seconds
The job exceeded the maximum time limit for jobs, and has been terminated.
```

I'm not able to see the logs in `test/logs` for this failure - looks like our travis config injects the log content into the travis output using the `after_failure` tag and maybe this isn't triggered by a timeout.

I would expect we terminate this test run after ~5 minutes after API fails to start.

Possible regression from https://github.com/medic/medic-webapp/commit/569c1257d5d73e4143d12e98ef42e70332193350 @garethbowen ?

**Comment by garethbowen** [comment]
It looks like Horti failed:

```
/home/travis/.nvm/versions/node/v10.15.0/lib/node_modules/horticulturalist/node_modules/pouchdb-core/lib/index.js:1285
    throw new Error('Invalid Adapter: ' + opts.adapter);
    ^
Error: Invalid Adapter: undefined
    at new PouchDB (/home/travis/.nvm/versions/node/v10.15.0/lib/node_modules/horticulturalist/node_modules/pouchdb-core/lib/index.js:1285:11)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v10.15.0/lib/node_modules/horticulturalist/src/dbs.js:44:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v10.15.0/lib/node_modules/horticulturalist/src/bootstrap.js:1:74)
```

We should investigate why this failed seemingly randomly.

Also, we should either retry or fail the build immediately when horti fails rather than timing out.

**Comment by garethbowen** [comment]
Maybe related to #5198

**Comment by kennsippell** [comment]
Locally, if I take the line `browser.driver.wait(listenForApi, 120 * 1000, 'API took too long to start up');` in `base.config.js` and change it to `browser.driver.wait(listenForApi, 100, 'API took too long to start up');` it when API isn't started I would expect it to timeout after 100ms. Instead I can run it for >5mins. 

Unsure of what is wrong here, but that timeout doesn't seem to get respect.

**Comment by garethbowen** [comment]
No AT required.
