### ISSUE TITLE
Flakey e2e test: registration transition submits new sms messages shows content

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5344]
It always seems to fail around midnight GMT.

```
Failures:
1) registration transition submits new sms messages shows content
  Message:
[31m    Expected 'LMP Jnne, Ago 20, 2019' to be 'LMP Jtat, Ago 19, 2019'.[0m
  Stack:
    Error: Failed expectation
        at checkAutoResponse (/home/travis/build/medic/medic/tests/e2e/registration-by-sms.js:268:95)
        at UserContext.it (/home/travis/build/medic/medic/tests/e2e/registration-by-sms.js:291:7)
        at /home/travis/build/medic/medic/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at schedulerExecute (/home/travis/build/medic/medic/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2974:25)
        at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
        at <anonymous>
  Message:
[31m    Expected 'LMP Jnne, Ago 20, 2019' to be 'LMP Jtat, Ago 19, 2019'.[0m
  Stack:
    Error: Failed expectation
        at checkScheduledTask (/home/travis/build/medic/medic/tests/e2e/registration-by-sms.js:276:80)
        at UserContext.it (/home/travis/build/medic/medic/tests/e2e/registration-by-sms.js:294:7)
        at /home/travis/build/medic/medic/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:1077:7)
        at ControlFlow.promise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2505:12)
        at schedulerExecute (/home/travis/build/medic/medic/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3084:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3067:27)
        at asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2974:25)
        at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
        at <anonymous>
```

**Comment by garethbowen** [comment]
Merged. No AT required.
