### ISSUE TITLE
Add support for firing REST requests when documents are created / changed

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5499]
For Muso SIH we want to be able to send SIH a referral when it comes in.

**Comment by SCdF** [comment]
Two more changes are needed:
 - We should move the credentials our of the app_settings into another location that can only be accessed by sentinel
 - We should support sending to different endpoints based on some kind of expression

**Comment by SCdF** [comment]
The documentation for this feature is in this PR: https://github.com/medic/medic-docs/pull/97
The code itself is in this PR: https://github.com/medic/medic/pull/5686

AT:
 - Effectively the documentation should be the instructions for AT: it should work as documented
 - In summary though: you should be able to configure the `outbound` config param, along with enabling the transition, which should push your custom structured data to whatever endpoint you configure. That push happens whenever the schedules are checked, which is every 5 min (or just restart Sentinel)
 - Currently there is a [bug in medic-os](https://github.com/medic/medic-os/issues/46) where the COUCH_NODE_NAME is incorrectly set. This will cause issues with this feature and needs to be worked around by manually

**Comment by newtewt** [comment]
One call out I've noticed while testing is we are logging the username and password in logs. We should sanitize that info.
```
-13 21:02:00]   "json": true,
[2019-06-13 21:02:00]   "auth": {
[2019-06-13 21:02:00]     "username": "admin",
[2019-06-13 21:02:00]     "password": "test-pass",
[2019-06-13 21:02:00]     "sendImmediately": true
[2019-06-13 21:02:00]   }
[2019-06-13 21:02:00] } 
```

**Comment by garethbowen** [comment]
Great catch! :relieved:

**Comment by newtewt** [comment]
Seems like we are trying to create a task for the settings document? I'm not sure about this one or how I got it to happen. I've been uploading different settings regularly.

```
[2019-06-14 13:51:56] 2019-06-14 13:51:56 INFO: Creating outbound task task:outbound:settings 
[2019-06-14 13:52:00] 2019-06-14 13:52:00 ERROR: Error running tasks: { Error: Mapping error for firstConfig/patient_age: cannot find doc.fields.patient_age_in_years on source document
[2019-06-14 13:52:00]     at Object.keys.forEach.dest (/srv/software/medic-sentinel/md5-iakSzEElXa0jU79eeeg7Q==/src/schedule/outbound.js:92:13)
[2019-06-14 13:52:00]     at Array.forEach (<anonymous>)
[2019-06-14 13:52:00]     at Object.map [as _map] (/srv/software/medic-sentinel/md5-iakSzEElXa0jU79eeeg7Q==/src/schedule/outbound.js:74:29)
[2019-06-14 13:52:00]     at p.then (/srv/software/medic-sentinel/md5-iakSzEElXa0jU79eeeg7Q==/src/schedule/outbound.js:210:40)
[2019-06-14 13:52:00]     at <anonymous>
[2019-06-14 13:52:00]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-06-14 13:52:00]   [stack]: 'Error: Mapping error for firstConfig/patient_age: cannot find doc.fields.patient_age_in_years on source document\n    at Object.keys.forEach.dest (/srv/software/medic-sentinel/md5-iakSzEElXa0jU79eeeg7Q==/src/schedule/outbound.js:92:13)\n    at Array.forEach (<anonymous>)\n    at Object.map [as _map] (/srv/software/medic-sentinel/md5-iakSzEElXa0jU79eeeg7Q==/src/schedule/outbound.js:74:29)\n    at p.then (/srv/software/medic-sentinel/md5-iakSzEElXa0jU79eeeg7Q==/src/schedule/outbound.js:210:40)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2019-06-14 13:52:00]   [message]: 'Mapping error for firstConfig/patient_age: cannot find doc.fields.patient_age_in_years on source document' } 

```

I'm kinda confused why the log shows this info. 

Specifically 
` [2019-06-13 20:52:40] 2019-06-13 20:52:40 INFO: Creating outbound task task:outbound:d4c87b55-9a95-4ecd-ad7b-5b398a318cd4 `
` [2019-06-13 20:52:40] 2019-06-13 20:52:40 INFO: task:outbound:d4c87b55-9a95-4ecd-ad7b-5b398a318cd4 already exists, ignoring `

The log looks like this
```
[2019-06-13 20:52:00] 2019-06-13 20:52:00 INFO: checking schedule again in 5 minutes
[2019-06-13 20:52:40] 2019-06-13 20:52:40 INFO: Creating outbound task task:outbound:d4c87b55-9a95-4ecd-ad7b-5b398a318cd4 
[2019-06-13 20:52:40] 2019-06-13 20:52:40 INFO: saved changes on doc d4c87b55-9a95-4ecd-ad7b-5b398a318cd4 seq 3125-g1AAAAJ7eJyd0LENwjAQBVBDkKBlApgA2efEJhVZgwpsBytECVQ0NDAGFbAJbAIDsENw7KA0EVKik_5Jd7pXXIYQGiVejMZqf1BJLCMCfIZNkcys-gLJSVEUaeJJhHp5bmZDHzgDAU03fyQ5NSkXNba1GGAGG5i3xaISW9XY0mKacCy4aoutS-xUY1eLBYRqpoOW2G5gEp1NM96tAo8ONG_DoDuBdwc-KjC1oGJ841PSCXw68FWBFwtKoCGjrBP4duDvhx8LciljwcOm0_QL3W-iDQ 
[2019-06-13 20:52:40] 2019-06-13 20:52:40 INFO: saved changes on doc 0dcc078c-ea35-4e2c-9574-1d1a91d405a3 seq 3126-g1AAAAJ7eJyd0EEKwjAQBdBoBd16Aj2BJJM2sSt7DVeapIZSWl25caPHcKXeRG-iB_AONU0qRShCy8AMzDBv8TOE0CjxYjRWu71KYhkR4DNsimTm1BdIToqiSBNPItTLc7Mb-sAZCGj6-SPJqelyUWOpxQAz2MC8LRaV2KrGlhbThGPBVVtsXWLHGrtYLCBUMx20xLYD09HJDONdK_DgQBMbBt0JvDnw_pOdYnzjU9IJfDjwWYFnC0qgIaOsE_hy4DfDtwW5lLHgYdNr-gHfb6IO 
[2019-06-13 20:52:40] 2019-06-13 20:52:40 INFO: task:outbound:d4c87b55-9a95-4ecd-ad7b-5b398a318cd4 already exists, ignoring 

```

**Comment by newtewt** [comment]
I figured out the issue with why settings is getting tagged. When making `"relevant_to": 'true'` it is processing the settings doc.

**Comment by newtewt** [comment]
I'm also seeing a document update conflict on gamma.dev. 

```
[2019-06-14 15:49:14] 2019-06-14 15:49:14 INFO: Loading transition "mark_for_outbound" 
[2019-06-14 15:49:31] 2019-06-14 15:49:31 INFO: Creating outbound task task:outbound:7c626a23-3310-4718-bf9d-0e842283fe96 
[2019-06-14 15:49:31] 2019-06-14 15:49:31 INFO: saved changes on doc 7c626a23-3310-4718-bf9d-0e842283fe96 seq 18048-g1AAAAJ7eJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____szKYk4AKJXOBYuzGqZYmZoYm2PTgMSlJAUgm2SMMqwAblmSZZJliaUaqYQ4gw-IRhhWADTM0tzBPNTYi1bAEkGH1cMM4FcCGWZobJiWlJZJoWB4LkGRoAFJA8-ZDXTcTEm5micmpRqSGG8TABRAD90NdyAk20MDS0sTYIpksAw9ADLwPNVAZbGBqmpFhqqkBWQY-gBgIC8NZkDA0NTMxMccahlkAwyOhEA 
[2019-06-14 15:49:31] 2019-06-14 15:49:31 INFO: task:outbound:7c626a23-3310-4718-bf9d-0e842283fe96 already exists, ignoring 
[2019-06-14 15:53:00] 2019-06-14 15:53:00 INFO: checking schedule again in 5 minutes 
[2019-06-14 15:53:00] 2019-06-14 15:53:00 INFO: Pushed 7c626a23-3310-4718-bf9d-0e842283fe96 to secondConfig 
[2019-06-14 15:53:00] 2019-06-14 15:53:00 ERROR: Failed to push 7c626a23-3310-4718-bf9d-0e842283fe96 to secondConfig: Document update conflict. 
[2019-06-14 15:53:00] 2019-06-14 15:53:00 ERROR: Document update conflict. 
```

**Comment by newtewt** [comment]
I've moved this back to in dev for review of the issues listed. I'm also going to spend some more time with the mapping portion and see if anything comes out from that.

**Comment by garethbowen** [comment]
Assigning to @SCdF as he's expected back from holiday today.

**Comment by SCdF** [comment]
> One call out so far I've noticed while testing is we are logging the username and password in logs.

Can you check the name of the deployed branch. Sounds like you've got the wrong one, it should be `5499_outbound_rest_feature` and not `5499_outbound_rest`, as the latter has various hacks to enable easy configuration creation for SIH.

> When making "relevant_to": 'true' it is processing the settings doc. Seems it picks up other things too. Not sure if that is expected but this seems like whomever is making this config should be sure they understand that they can basically send any doc to a remote service.

Based on the documentation, what was your expectation in this situation? In other words, how can we change the documentation to steer people right the first time?

>  document update conflict

Can you provide more details here, as in what you did to cause the issue (it looks like you had two configs? Did both fire and cause a conflict or something)? Once we've worked out what code you were ATing I can look into it.

**Comment by newtewt** [comment]
Yeah that's my bad. I have applied the correct branch and I'll run through it. 

> Outbound push allows configurers to have single reports generated by CHWs or others trigger outbound REST requests using the data in that report. For example, upon receiving a referral report you could send that referral to an external facility system that will manage and process that event.

The documentation and my assumption makes me think reports. Maybe I'm miss understanding the word report but I assumed it would have only been data that was processed through a form in our app. Like a referral, pregnancy, muting, death, etc... I would explicitly state this can potentially send any couchdb doc that our app saves if configured to do so or incorrectly configured to do so.

I noticed today that creating users will also trigger given the right relevant_to condition. Which I could see use for notifying another system of a new user creation so I don't know that it's necessarily a bad thing. 

`[2019-06-17 15:05:08] 2019-06-17 15:05:08 INFO: Creating outbound task task:outbound:org.couchdb.user:test1 `

I'll work on the document update conflict because I'm struggling to figure out exactly what is causing it to occur.

**Comment by newtewt** [comment]
The logging is gone in the correct branch. 

I keep running into the document update conflict. However, I'm not seeing a clear pattern as to why. When it happens once it begins happening for every outbound request. Below is my config

```
  "outbound": {
    "firstConfig": {
      "relevant_to": "(doc.form && doc.form === 'pregnancy') || doc.type === 'user-settings'",
      "destination": {
        "base_url": "http://localhost:3000",
        "auth": {
          "type": "basic",
          "username": "admin",
          "password_key": "test"
        },
        "path": "/"
      },
      "mapping": {
        "patient_age": {
          "expr": "true ? 'test1': 'test2'"
        }
      }
    },
    "secondConfig": {
      "relevant_to": "doc.type === 'data_record' && doc.form === 'on'",
      "destination": {
        "base_url": "http://localhost:3000",
        "auth": {
          "type": "basic",
          "username": "bob",
          "password_key": "test1"
        },
        "path": "/test/red1"
      },
      "mapping": {
        "doc": "doc"
      }
    }
  }
```

**Comment by SCdF** [comment]
> The documentation and my assumption makes me think reports

That's a great point. The intention is anything (in the same way that couch2pg is anything), so we should change the documentation from talking about reports to talking about records or maybe documents, as well as adding a note reminding folks that it sends anything.

I've updated the documentation PR: https://github.com/medic/medic-docs/pull/97

> document update conflict

I took a look at the code and found an incorrectly chained promise (the old `.then(fooFn())` vs. `.then(() => fooFn())`) which was almost certainly causing this issue. The new build should no longer have this problem, check it out!

**Comment by newtewt** [comment]
I've tried the latest `5499_outbound_rest_feature` branch and the first attempt to send a outbound request is showing the conflict error.  I must be doing something wrong. Here's the list of steps I've taken. 

Start Medic OS - This creates a blank instance on 3.2.1 in docker. 
Updated COUCH_NODE_NAME.
Updated to 3.4.0
Apply standard config from master using medic-conf 2.0.4
Seed some data from csv-to-docs
Apply `5499_outbound_rest_feature` branch
Add the credentials via fauxton
Apply config.
Watching the sentinel logs it seems to be creating an outbound task for existing docs. I keep refreshing the mango query and see the number grow for a bit.
After the 5 minute schedule sentinel attempts to send and my local express server catches all those requests and the medic-sentinel.log is filled with the errors shown below. 

 
```

[2019-06-18 14:05:56] 2019-06-18 14:05:56 INFO: task:outbound:fe4945de-5fce-55f3-953d-90424eac848b already exists, ignoring 
[2019-06-18 14:07:01] 2019-06-18 14:07:01 INFO: Pushed 007d1d4c-0d9e-56f9-af7e-d38738ff9b93 to firstConfig 
[2019-06-18 14:07:01] 2019-06-18 14:07:01 ERROR: Failed to push 007d1d4c-0d9e-56f9-af7e-d38738ff9b93 to firstConfig: Document update conflict. 
[2019-06-18 14:07:01] 2019-06-18 14:07:01 ERROR: Document update conflict. 
[2019-06-18 14:07:01] 2019-06-18 14:07:01 INFO: Pushed 03537ab0-c818-51fd-b7bc-78f7abed571e to firstConfig 
[2019-06-18 14:07:01] 2019-06-18 14:07:01 ERROR: Failed to push 03537ab0-c818-51fd-b7bc-78f7abed571e to firstConfig: Document update conflict. 
```

**Comment by newtewt** [comment]
Ok, so I've found another issue but isn't really breaking anything but would be something we might want to clean up. This seems like it'd like never happen in prod as I assume the settings aren't changed very frequently.

Upload a config that has multiple outbound configs.
sync a doc that would match one of the relevant_to for the multiple config
Before sentinel processes. Remove the config that the queue doc in the last step would have been generated from.
The error below is shown in the log.


```
[2019-06-18 17:41:00] 2019-06-18 17:41:00 ERROR: Error running tasks: { TypeError: Cannot read property 'mapping' of undefined
[2019-06-18 17:41:00]     at mapDocumentToPayload (/srv/software/medic-sentinel/md5-tdALZ2xdYjOm4ANjng2l7w==/src/schedule/outbound.js:77:22)
[2019-06-18 17:41:00]     at singlePush (/srv/software/medic-sentinel/md5-tdALZ2xdYjOm4ANjng2l7w==/src/schedule/outbound.js:194:19)
[2019-06-18 17:41:00]     at p.then (/srv/software/medic-sentinel/md5-tdALZ2xdYjOm4ANjng2l7w==/src/schedule/outbound.js:258:61)
[2019-06-18 17:41:00]     at <anonymous>
[2019-06-18 17:41:00]     at process._tickCallback (internal/process/next_tick.js:188:7)
[2019-06-18 17:41:00]   [stack]: 'TypeError: Cannot read property \'mapping\' of undefined\n    at mapDocumentToPayload (/srv/software/medic-sentinel/md5-tdALZ2xdYjOm4ANjng2l7w==/src/schedule/outbound.js:77:22)\n    at singlePush (/srv/software/medic-sentinel/md5-tdALZ2xdYjOm4ANjng2l7w==/src/schedule/outbound.js:194:19)\n    at p.then (/srv/software/medic-sentinel/md5-tdALZ2xdYjOm4ANjng2l7w==/src/schedule/outbound.js:258:61)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
[2019-06-18 17:41:00]   [message]: 'Cannot read property \'mapping\' of undefined' } 
```

**Comment by SCdF** [comment]
OK, I dug a little deeper and found the real culprit of the conflicts, and have fixed them. I also dealt with situations where the config can no longer be found: it will log out a warning and then remove it from the queue (the presumption being that you intentionally removed this outbound configuration and thus existing tasks that had this should just remove the push from their queue):

```
2019-06-19 12:12:35 WARN: Unable to push 2e55d5f9-1c70-411d-9d76-ff3b9d501bd7 for muso-sih because this outbound config no longer exists, clearing task
```

Once the branch rebuilds feel free to retest!

**Comment by newtewt** [comment]
AWWWEEESSOMMMEEEEE that seems to have done it. No errors. Sending as expected. Closing this out.  @SCdF  there are conflicts needing resolved in that branch or I'd squash/merge.

**Comment by garethbowen** [comment]
Merged into `master`.

**Comment by michaelkohn** [comment]
The documentation for this can be found [here](https://github.com/medic/medic-docs/blob/master/configuration/outbound.md).
