### ISSUE TITLE
The accept_patient_reports throws an error

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5671]
**Describe the bug**
When searching for a `validRegistration`, `accept_patient_reports` assumes that if the registration has a `scheduled_tasks` property, it must also be an array with at least one element. 
If the array is empty, accessing a property of the 1st element of the array throws an error:

https://github.com/medic/medic/blob/master/shared-libs/transitions/src/transitions/accept_patient_reports.js#L134

```
if (registration.scheduled_tasks) {
  var scheduledTasks = _.sortBy(registration.scheduled_tasks, 'due');       
  if (visitReportedDate < moment(scheduledTasks[0].due)) {
......
```

**To Reproduce**
1. Install 3.4 or 3.5
2. Configure accept_patient_reports to run on your desired form (`THE_FORM`)
3. Add a registration for a patient that has a `scheduled_tasks` equal to an empty array
4. Submit `THE_FORM` for the same patient

**Expected behavior**
`accept_patient_reports` should run successfully on your `THE_FORM` report

**What actually happens**
`accept_patient_reports` does not run successfully on your report and depending on your configuration, an error might be added to the doc:

![image](https://user-images.githubusercontent.com/35681649/57828031-99d0e900-77b2-11e9-904b-0f473fe65a4c.png)

**Logs**
```
2019-05-14 14:20:59 ERROR: transition accept_patient_reports errored on doc 7412174f-407f-4aec-8fa1-6a246f2b437a seq 142909-g1AAAAJ7eJzLYWBg4MhgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMiQ5L8____szKYkxgYXLbkAsXYk8yTU41TTLDpwWNSkgKQTLKHG-YaCDYs2djY1Cw1jVTDHECGxSNcFgI2zDTVKDXZ0JJUwxJAhtXDDfN8BTbM0MTY3MDImETD8liAJEMDkAKaNx9ioDs3xKsWQM-S7DqIgQsgBu6HevcL2MDEFANjExPyXHgAYuB9aGRMARtokGpqnkRyzEIMfAAxEBYh6ZAwtDSwTDU3x6Y1CwAGVKTE: {"message":"Cannot read property 'due' of undefined","stack":"TypeError: Cannot read property 'due' of undefined\n    at findValidRegistration (/home/diana/projects/medic-340/sentinel/src/transitions/accept_patient_reports.js:141:58)\n    at addReportUUIDToRegistration (/home/diana/projects/medic-340/sentinel/src/transitions/accept_patient_reports.js:183:55)\n    at module.exports.silenceRegistrations.err (/home/diana/projects/medic-340/sentinel/src/transitions/accept_patient_reports.js:250:9)\n    at /home/diana/projects/medic-340/sentinel/src/transitions/accept_patient_reports.js:205:7\n    at /home/diana/projects/medic-340/sentinel/node_modules/async/dist/async.js:473:16\n    at iteratorCallback (/home/diana/projects/medic-340/sentinel/node_modules/async/dist/async.js:1064:13)\n    at /home/diana/projects/medic-340/sentinel/node_modules/async/dist/async.js:969:16\n    at Object._silenceReminders (/home/diana/projects/medic-340/sentinel/src/transitions/accept_patient_reports.js:99:12)\n    at /home/diana/projects/medic-340/sentinel/src/transitions/accept_patient_reports.js:202:22\n    at /home/diana/projects/medic-340/sentinel/node_modules/async/dist/async.js:3110:16"} 
```

**Environment**
- Instance: Live 3.4 instance (https://github.com/medic/medic-projects/issues/6298), localhost
- Client platform: Linux
- App: Sentinel
- Version: 3.4, 3.5

**Comment by dianabarsan** [comment]
Ready for AT on `5671-make-transition--more-tolerant`.
Post AT, please do not merge, a shared library needs to be published and dependencies bumped.

**Comment by ngaruko** [comment]
LTGM. Back to you @dianabarsan to merge when ready!
