### ISSUE TITLE
e2e tests fail at 0000 GMT on travis

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5730]
I've noticed this a few times. Restarting the build fixes it.

```
  registration transition
    submits new sms messages
      ✗ shows content (10 secs)
        - Expected 'LMP Alh, Jan 2, 2020' to be 'LMP Jtan, Jan 1, 2020'.
            at checkAutoResponse (/home/travis/build/medic/medic/tests/e2e/registration-by-sms.js:268:95)
            at UserContext.it (/home/travis/build/medic/medic/tests/e2e/registration-by-sms.js:291:7)
            at /home/travis/build/medic/medic/node_modules/jasminewd2/index.js:112:25
            at new ManagedPromise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:1077:7)
            at ControlFlow.promise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2505:12)
            at schedulerExecute (/home/travis/build/medic/medic/node_modules/jasminewd2/index.js:95:18)
            at TaskQueue.execute_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3084:14)
            at TaskQueue.executeNext_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3067:27)
            at asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2974:25)
            at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
        - Expected 'LMP Alh, Jan 2, 2020' to be 'LMP Jtan, Jan 1, 2020'.
            at checkScheduledTask (/home/travis/build/medic/medic/tests/e2e/registration-by-sms.js:276:80)
            at UserContext.it (/home/travis/build/medic/medic/tests/e2e/registration-by-sms.js:294:7)
            at /home/travis/build/medic/medic/node_modules/jasminewd2/index.js:112:25
            at new ManagedPromise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:1077:7)
            at ControlFlow.promise (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2505:12)
            at schedulerExecute (/home/travis/build/medic/medic/node_modules/jasminewd2/index.js:95:18)
            at TaskQueue.execute_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3084:14)
            at TaskQueue.executeNext_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3067:27)
            at asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2974:25)
            at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
```

**Comment by garethbowen** [comment]
Duplicate of #5344
