### ISSUE TITLE
Requesting feedback docs fails with Error about long string

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5851]
Trying to pull feedback docs for Muso:
`node scripts/get_users_meta_docs.js --mode interactive --type feedback https://admin:abcd@muso-mali.app.medicmobile.org/medic-users-meta`

Seeing this error:
```
{ FetchError: invalid json response body at https://muso-mali.app.medicmobile.org/medic-users-meta/_all_docs?include_docs=true&startkey=%22feedback-%22&endkey=%22feedback-%EF%BF%B0%22 reason: Cannot create a string longer than 0x3fffffe7 characters
    at /home/kenn/webapp/node_modules/node-fetch/lib/index.js:241:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://muso-mali.app.medicmobile.org/medic-users-meta/_all_docs?include_docs=true&startkey=%22feedback-%22&endkey=%22feedback-%EF%BF%B0%22 reason: Cannot create a string longer than 0x3fffffe7 characters',
  type: 'invalid-json' }
```

**Comment by wtekeu** [comment]
Fixed and merged
