### ISSUE TITLE
Translation throwing errors in production

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5863]
There are tens of thousands (hundreds of thousands?) of feedback documents for Muso-Mali users with this stack. 

```
Expected \",\", \"}\", or [\\t-\\r \\x85‎‏

] but \"r\" found."
at kt (https://muso-mali.app.medicmobile.org/js/inbox.js:3:1887992)
at parse (https://muso-mali.app.medicmobile.org/js/inbox.js:3:1894315)\n    
at o.compile (https://muso-mali.app.medicmobile.org/js/inbox.js:3:1897032)\n    
at s.compile (https://muso-mali.app.medicmobile.org/js/inbox.js:3:1900517)\n    
at Object.o.interpolate (https://muso-mali.app.medicmobile.org/js/inbox.js:3:2835331)\n    
at ...
```

Based on discussion with Diana:
> it's a translation error which has existed for very long but was not being reported by the prior feedback mechanism. I suspect lots of projects (that use languages that are not english or french) have this problem.

We should fix this. If it cannot be fixed, it should be silenced. If it is known, understood, and not actionable it should be not be uploaded via feedback documents.

**Comment by garethbowen** [comment]
Priority increased - this many docs being created with hurt bandwidth and performance.

**Comment by garethbowen** [comment]
@kennsippell Is there a workaround for this?

**Comment by kennsippell** [comment]
I'm unclear on the code path which actually triggers this.  Would require a bit of an investigation on my end. Might be worth looking into potential workarounds in 3.7 timeframe, and if a fix is required, pursue it in 3.8?

**Comment by garethbowen** [comment]
I couldn't reproduce the exact error but I've reproduced a parsing failure.

1. Go to App Settings > Languages > Application Text
2. Find the "n.month" translation key and click it to edit it
3. Change the English value to "{MONTHS, plurala, one{1 month} other{# months}}". This is invalid because there should be a comma not an "a" directly after the word "plural".
4. Log in to the app as a restricted user
5. Go to People and select a person

See this error in the console:

![Screenshot from 2019-09-16 16-58-54](https://user-images.githubusercontent.com/2064938/64935127-4fb45d00-d8a3-11e9-84b5-521f58bb184f.png)

```
SyntaxError: Expected "," but "a" found.
    at Xr (http://localhost:5988/js/inbox.js:137511:25365)
    at parse (http://localhost:5988/js/inbox.js:137511:33520)
    at r.value (http://localhost:5988/js/inbox.js:137511:41389)
    at r.value (http://localhost:5988/js/inbox.js:137511:48244)
    at Object.$translateInterpolator.interpolate (http://localhost:5988/js/inbox.js:206094:30)
    at determineTranslation (http://localhost:5988/js/inbox.js:27799:50)
    at $translate (http://localhost:5988/js/inbox.js:27374:9)
    at updateTranslation (http://localhost:5988/js/inbox.js:29016:13)
    at updateTranslations (http://localhost:5988/js/inbox.js:29003:15)
    at observeElementTranslation (http://localhost:5988/js/inbox.js:28929:11)
```

**Comment by garethbowen** [comment]
How it looks now:

![Screenshot from 2019-09-16 22-20-10](https://user-images.githubusercontent.com/2064938/64950720-2d850400-d8d0-11e9-9ecb-856a1ad946bc.png)

I've also gone through the default translations and fixed any syntax errors I could find.

**Comment by garethbowen** [comment]
Ready for AT in `5863-catch-interpolation-errors`

**Comment by newtewt** [comment]
Looks good to me. I see the console warning instead of error and looking at the local meta database there isn't an entry for those failures as opposed to the previous version there were.
