### ISSUE TITLE
Flakey test: "Navigation tests : should open Report bug"

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5890]
This has failed in a few builds:

```
  Navigation tests : 
    [32mâœ“ should open Messages tab[39m (0.734 sec)
    [32mâœ“ should open tasks tab[39m (0.413 sec)
    [32mâœ“ should open Reports or History tab[39m (0.794 sec)
    [32mâœ“ should open Contacts or Peoples tab[39m (0.423 sec)
    [32mâœ“ should open Analytics or Targets tab[39m (0.289 sec)
    [32mâœ“ should open Configuration wizard[39m (2 secs)
    [32mâœ“ should open Guided tour[39m (1 sec)
    [32mâœ“ should open About[39m (1 sec)
    [32mâœ“ should open User settings[39m (1 sec)
    [31mâœ— should open Report bug[39m (0.802 sec)
      [31m- [39m[31mFailed: stale element reference: element is not attached to the page document
        (Session info: headless chrome=76.0.3809.100)
        (Driver info: chromedriver=75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}),platform=Linux 4.4.0-101-generic x86_64)[39m
        (Session info: headless chrome=76.0.3809.100)
        (Driver info: chromedriver=75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}),platform=Linux 4.4.0-101-generic x86_64)
          at Object.checkLegacyResponse (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/error.js:546:15)
          at parseHttpResponse (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/http.js:509:13)
          at doSend.then.response (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/http.js:441:30)
          at process._tickCallback (internal/process/next_tick.js:68:7)
      From: Task: WebElement.getText()
          at thenableWebDriverProxy.schedule (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
          at WebElement.schedule_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
          at WebElement.getText (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/webdriver.js:2277:17)
          at actionFn (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:89:44)
          at Array.map (<anonymous>)
          at actionResults.getWebElements.then (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:461:65)
          at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2927:27)
          at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
          at process._tickCallback (internal/process/next_tick.js:68:7)Error
          at ElementArrayFinder.applyAction_ (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:459:27)
          at ElementArrayFinder.(anonymous function).args [as getText] (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:91:29)
          at ElementFinder.(anonymous function).args [as getText] (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:831:22)
          at elements.each.element (/home/travis/build/medic/medic/tests/helper.js:52:19)
          at arr.map (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:628:33)
          at Array.map (<anonymous>)
          at asElementFinders_.then (/home/travis/build/medic/medic/node_modules/protractor/built/element.js:627:28)
          at ManagedPromise.invokeCallback_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2927:27)
          at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
          at process._tickCallback (internal/process/next_tick.js:68:7)
      From: Task: Run it("should open Report bug") in control flow
          at UserContext.<anonymous> (/home/travis/build/medic/medic/node_modules/jasminewd2/index.js:94:19)
          at /home/travis/build/medic/medic/node_modules/jasminewd2/index.js:64:48
          at ControlFlow.emit (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/events.js:62:21)
          at ControlFlow.shutdown_ (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2674:10)
          at shutdownTask_.MicroTask (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2599:53)
          at MicroTask.asyncRun (/home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:2728:9)
          at /home/travis/build/medic/medic/node_modules/selenium-webdriver/lib/promise.js:668:7
          at process._tickCallback (internal/process/next_tick.js:68:7)
      From asynchronous test: 
      Error
          at Suite.describe (/home/travis/build/medic/medic/tests/e2e/common/common.specs.js:55:3)
          at Object.<anonymous> (/home/travis/build/medic/medic/tests/e2e/common/common.specs.js:4:1)
          at Module._compile (internal/modules/cjs/loader.js:778:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
          at Module.load (/home/travis/build/medic/medic/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
          at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
          at Function.Module._load (internal/modules/cjs/loader.js:585:3)
          at Module.require (internal/modules/cjs/loader.js:692:17)
          at require (internal/modules/cjs/helpers.js:25:18)
          at Array.forEach (<anonymous>)
          at Function.promise (/home/travis/build/medic/medic/node_modules/q/q.js:682:9)
          at _fulfilled (/home/travis/build/medic/medic/node_modules/q/q.js:834:54)
          at /home/travis/build/medic/medic/node_modules/q/q.js:863:30
          at Promise.promise.promiseDispatch (/home/travis/build/medic/medic/node_modules/q/q.js:796:13)
          at /home/travis/build/medic/medic/node_modules/q/q.js:604:44
          at runSingle (/home/travis/build/medic/medic/node_modules/q/q.js:137:13)
          at flush (/home/travis/build/medic/medic/node_modules/q/q.js:125:13)
          at process._tickCallback (internal/process/next_tick.js:61:11)
    [32mâœ“ should open Configuration app[39m (1 sec)
```

**Comment by garethbowen** [comment]
No AT required.
